class ModifySkillsAndContactTypesData < ActiveRecord::Migration
  def self.up
    Contact.connection.execute("delete from skills")
    Contact.connection.execute("delete from contacttypes")

	Skill.create(:description => "Appliance Repair", :is_trade_skill => 1)
	Skill.create(:description => "Carpentry", :is_trade_skill => 1)
	Skill.create(:description => "Cleaning")
	Skill.create(:description => "Concrete", :is_trade_skill => 1)
	Skill.create(:description => "Crane Operator", :is_trade_skill => 1)
	Skill.create(:description => "Debris Pickup")
	Skill.create(:description => "Drywall", :is_trade_skill => 1)
	Skill.create(:description => "Electrical", :is_trade_skill => 1)
	Skill.create(:description => "Fencing", :is_trade_skill => 1)
	Skill.create(:description => "Flooring", :is_trade_skill => 1)
	Skill.create(:description => "Foundation", :is_trade_skill => 1)
	Skill.create(:description => "Gas", :is_trade_skill => 1)
	Skill.create(:description => "Glazing", :is_trade_skill => 1)
	Skill.create(:description => "Has Truck", :is_trade_skill => 1)
	Skill.create(:description => "Hauling")
	Skill.create(:description => "Heat/AC", :is_trade_skill => 1)
	Skill.create(:description => "Insulation", :is_trade_skill => 1)
	Skill.create(:description => "Masonry", :is_trade_skill => 1)
	Skill.create(:description => "Organizing")
	Skill.create(:description => "Painting", :is_trade_skill => 1)
	Skill.create(:description => "Pest Control", :is_trade_skill => 1)
	Skill.create(:description => "Plumbing", :is_trade_skill => 1)
	Skill.create(:description => "Roofing", :is_trade_skill => 1)
	Skill.create(:description => "Scaffolding", :is_trade_skill => 1)
	Skill.create(:description => "Scraping")
	Skill.create(:description => "Sheet Rock", :is_trade_skill => 1)
	Skill.create(:description => "Tile", :is_trade_skill => 1)
	Skill.create(:description => "Trash")
	Skill.create(:description => "Welding", :is_trade_skill => 1)
	Skill.create(:description => "Yard Work")

	Contacttype.create(:description => "Normal Volunteer")
	Contacttype.create(:description => "Skilled Trade Volunteer")
	Contacttype.create(:description => "Office Volunteer")
	Contacttype.create(:description => "Board Member")
	Contacttype.create(:description => "Committee Member")
	Contacttype.create(:description => "Area Captain")
	Contacttype.create(:description => "House Captain")
	Contacttype.create(:description => "House Liaison")
	Contacttype.create(:description => "House Sponsor")
	Contacttype.create(:description => "Homeowner Interviewer")
	Contacttype.create(:description => "Homeowner")
	
  end
 
  def self.down
    Contact.connection.execute("delete from skills")
    Contact.connection.execute("delete from contacttypes")

    Skill.create(:description => "Appliance Repair", :is_trade_skill => 1)
    Skill.create(:description => "Carpentry", :is_trade_skill => 1)
    Skill.create(:description => "Cleaning", :is_house_skill => 1)
    Skill.create(:description => "Concrete", :is_trade_skill => 1)
    Skill.create(:description => "Crane Operator", :is_trade_skill => 1)
    Skill.create(:description => "Drywall", :is_trade_skill => 1)
    Skill.create(:description => "Electrical", :is_trade_skill => 1)
    Skill.create(:description => "Flooring", :is_trade_skill => 1)
    Skill.create(:description => "Foundation", :is_trade_skill => 1)
    Skill.create(:description => "Gas", :is_trade_skill => 1)
    Skill.create(:description => "Glazing", :is_trade_skill => 1)
    Skill.create(:description => "Hauling", :is_house_skill => 1)
    Skill.create(:description => "Heat/AC", :is_trade_skill => 1)
    Skill.create(:description => "Insulation", :is_trade_skill => 1)
    Skill.create(:description => "Masonry", :is_trade_skill => 1)
    Skill.create(:description => "Painting", :is_trade_skill => 1)
    Skill.create(:description => "Pest Control", :is_trade_skill => 1)
    Skill.create(:description => "Plumbing", :is_trade_skill => 1)
    Skill.create(:description => "Roofing", :is_trade_skill => 1)
    Skill.create(:description => "Scaffolding", :is_trade_skill => 1)
    Skill.create(:description => "Scraping", :is_house_skill => 1)
    Skill.create(:description => "Sheet Rock", :is_trade_skill => 1)
    Skill.create(:description => "Tile", :is_trade_skill => 1)
    Skill.create(:description => "Trash", :is_house_skill => 1)
    Skill.create(:description => "Welding", :is_trade_skill => 1)
    Skill.create(:description => "Yard Work", :is_house_skill => 1)
  
    Skill.create(:description => "Waste Management", :is_house_skill => 1)
    Skill.create(:description => "Organizing", :is_contact_skill => 1)
    Skill.create(:description => "Public Relations", :is_contact_skill => 1)
    Skill.create(:description => "Community Outreach", :is_contact_skill => 1)
    Skill.create(:description => "Special Events / Fundraising", :is_contact_skill => 1)
    Skill.create(:description => "Publicity", :is_contact_skill => 1)
    Skill.create(:description => "Data Entry", :is_contact_skill => 1)
        
    Contacttype.create(:description => "Normal Volunteer")
    Contacttype.create(:description => "Skilled Trade Volunteer")
    Contacttype.create(:description => "Office Volunteer")
    Contacttype.create(:description => "Money Contributor")
    Contacttype.create(:description => "In-Kind Contributor")
    Contacttype.create(:description => "House Sponsor")
    Contacttype.create(:description => "Homeowner")
    Contacttype.create(:description => "Board Member")
    Contacttype.create(:description => "Committee Member")

    Contacttype.create(:description => "House Captain")
    Contacttype.create(:description => "House Liaison")

  end
end